services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v2
    container_name: sh-pocketid-0101
    restart: unless-stopped
    environment:
      - ENCRYPTION_KEY=${POCKETID_ENCRYPTION_KEY}
      - MAXMIND_LICENSE_KEY=${POCKETID_MAXMIND_LICENSE_KEY}
      - TRUST_PROXY=true
      - PUID=1000
      - PGID=1000
    ports:
      - 1411:1411
    volumes:
      - "/opt/docker/projects/pocketid/data:/app/data"
    networks:
      - pocketid
    healthcheck:
      test: ["CMD", "/app/pocket-id", "healthcheck"]
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s

networks:
  pocketid:
    driver: bridge
