version: "3.5"
services:
  glances:
    container_name: glances11
    image: joweisberg/glances:latest
    restart: unless-stopped
    pid: host
    ports:
      - 61208:61208
    environment:
      - TZ=Europe/Stockholm
      - GLANCES_OPT=--webserver
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./glances:/glances/conf
    networks: {}