ui:
  default-sort-by: group

connectivity:
  checker:
    target: 9.9.9.9:53
    interval: 60s

icmp-test: &test
  interval: 1s
  client:
    timeout: 10s
  conditions:
    - "[CONNECTED] == true"

icmp-defaults: &icmp
  interval: 60s
  client:
    timeout: 10s
  conditions:
    - "[CONNECTED] == true"

tcp-defaults: &tcp
  interval: 10s
  client:
    timeout: 10s
  conditions:
    - "[CONNECTED] == true"

ssh-defaults: &ssh
  interval: 120s
  client:
    timeout: 10s
  conditions:
    - "[CONNECTED] == true"

dns-defaults: &dns
  interval: 5m
  url: "9.9.9.9"
  client:
    timeout: 10s
  conditions:
    - "[DNS_RCODE] == NOERROR"

cert-defaults: &certs
  interval: 60s
  client:
    timeout: 10s
  conditions:
    - "[STATUS] == 200"
    - "[CERTIFICATE_EXPIRATION] > 48h"
###########################
endpoints:

  - name:  infra-0101-ping
    <<: *icmp
    group: vm
    url: "icmp://172.16.23.6"

  - name:  heavy-ping
    <<: *icmp
    group: xcpng
    url: "icmp://172.16.21.2"

  - name:  middy-ping
    <<: *icmp
    group: xcpng
    url: "icmp://172.16.21.3"

  - name:  sexy-ping
    <<: *icmp
    group: xcpng
    url: "icmp://172.16.21.4"

  - name:  xos-0101-ping
    <<: *icmp
    group: vm
    url: "icmp://172.16.21.5"

  - name: blog-ping
    <<: *icmp
    group: hosted
    url: "icmp://kaywozplayz.krypi.net"

  - name: blog-DNS
    <<: *dns
    group: hosted
    dns:
      query-type: "A"
      query-name: "kaywozplayz.krypi.net"

  - name: blog-Certs
    <<: *certs
    group: hosted
    url: "https://kaywozplayz.krypi.net"

  - name: npm-ping
    <<: *icmp
    group: docker
    url: "icmp://172.16.23.6"

  - name: socket-proxy-tcp
    <<: *tcp
    group: docker
    url: "tcp://172.16.23.6:2375"

  - name: sexy-ssh
    <<: *tcp
    group: xcpng
    url: ssh://172.16.21.4:22
    username: ""
    password: ""

  - name: test
    <<: *test
    group: test
    url: "icmp://9.9.9.9"

    ## sample badge as: http://172.16.23.6:8082/api/v1/endpoints/xcpng_sexy-ping/uptimes/7d/badge.svg
