shape: sequence_diagram
user -> securityresponsible: i need someone to investigate sus user!
securityresponsible -> servicelead: here, please take care of it.
servicelead -> sirt: here, please investigate.
sirt -> user: gief deets plz!
user -> sirt: here u go!
servicelead -> user: here's what's happening, so u know.
sirt -> servicelead: who can provide me more logs?
servicelead -> esc_point1: hey, can you help?
esc_point1 -> servicelead: not me, talk to the other guy.
servicelead -> esc_point2: i was told you can help.
esc_point2 -> servicelead: any of you can do it in the service request portal.
esc_point2 -> sirt: any of you can do it in the service request portal.
esc_point2 -> user: any of you can do it in the service request portal.
sirt -> esc_point2: but i need logs, not personal data.
esc_point2 -> sirt: does not matter, all data needs a request.
user -> datarequestform: ???
sirt -> datarequestform: ???
servicelead -> datarequestform: ???