shape: sequence_diagram
user -> sirt: i need someone to investigate sus user!
sirt -> usermanager: do you agree?
usermanager -> sirt: yes, please investigate!
sirt -> sirtlead: here are the findings
sirtlead -> sirt: ill disseminate, or escalate!
sirtlead -> user: here's whats happened!
