## global
vars: {
  d2-config: {
    layout-engine: elk
    sketch: true
  }
}

direction: right
title: krypi.net cloudops @grunty {
  near: top-center
  shape: text
  style: {
    font-size: 35
    bold: true
    underline: true
  }
}



## objects

##grunty.baremetal: 8c\n64gb\n240gb\n gtx4090\n .{
 ## shape: image
 ## icon: https://hostkey.com/hk/images/logo.svg
# icon.near: top-center
 # label.near: bottom-right
 ## style: {
  ##  stroke: black
  ##  font-color: black
   ## stroke-dash: 3
   ## fill: lightgrey
  ## opacity: 1
  ##  font-size: 20
 ## }
 
##}
##grunty.grunty: Grunty{ 
grunty:  {
  icon: https://www.svgrepo.com/download/484343/server-like.svg
  shape: image
  style: {
    stroke: black
    font-color: black
    stroke-dash: 3
    fill: lightgrey
    opacity: 1
  }


}
public_links:links {
  shape: cloud
  direction: right
  style: {
    stroke: black
    font-color: black
    stroke-dash: 3
    fill: white
    opacity: 1
  }
}
public_links.links: |md
 
[folding at home](https://folding.extremeoverclocking.com/user_summary.php?s=&u=378752)

|

app stacks.style: {
  fill: lightgrey
  opacity: 1
  3d: true
  stroke: black
  stroke-width: 5
}

proxy.style: {
  fill: orange
  opacity: 1
  3d: true
  stroke: black
  stroke-width: 5
}


app stacks.compute: {
  label: COMPUTE\n archivewarrior\n foldingathome\n ollama\n open-webui 
  style: {
    fill:"#f9f641"
  }
}

app stacks.honeypot: {
  label: HONEYPOT \n t-potce\n beelzebub\n galah\n
  style: {
    fill:"#ec4e2c"
  }
}

app stacks.infra: {
  label: INFRA \n tailscale\n beszel\n dozzle\n docker-socketproxy\n dockge
  style: {
    fill:"#9df941"
  }
}

## connections

grunty -- app stacks <- proxy <- public_links {
  style.stroke: black
  style.animated:true
  style.opacity: 1
  style.3d: true
  style.stroke: black
  style.stroke-width: 5
}


## other
