title: d2 {
  near: top-left
  shape: text
  style: {
    font-size: 29
    bold: true
    underline: true
  }
}

vars: {
  d2-config: {
    layout-engine: dagre
    # Terminal theme code
    theme-id: 300
    sketch: true
  }
}
style: {
  fill: lightgrey
  stroke: FireBrick
  stroke-width: 2
}

# compute
krypinet_h0me0ps.physical.compute.hypervisors.plenty-penguin.icon: https://www.servethehome.com/wp-content/uploads/2023/09/ASUS-ExpertCenter-PN42-Front-Angle.jpg
krypinet_h0me0ps.physical.compute.hypervisors.plenty-penguin.style.fill: lightblue
krypinet_h0me0ps.physical.compute.hypervisors.wally-wombat.style.fill: lightblue
krypinet_h0me0ps.physical.compute.hypervisors.wally-wombat.icon: https://www.servethehome.com/wp-content/uploads/2023/08/CWWK-N305-4x-2.5GbE-Rear.jpg
krypinet_h0me0ps.physical.compute.hypervisors.sexy-serval.style.fill: lightblue
krypinet_h0me0ps.physical.compute.hypervisors.sexy-serval.icon: https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEje4_PBv5ZTOy8CPjTf243_992XCtsC3ZG3yMe8lwkfRfSB-UjbPctl5N-b2BRDiAL8XQBKbz864d2KrQx13bHApg57FDzqkWBBxlnxb_G4yqp6Pe9Yjo9zdKHdAWLWm7IQRc7b-2e8zFo7XB8_dNyuB1kY6mfB042N7TuZWpICoyxIgwReeVwVvF07yds/s1000/akasa3.jpg
krypinet_h0me0ps.physical.compute.hypervisors.edgy-elephant.style.fill: lightblue
krypinet_h0me0ps.physical.compute.hypervisors.edgy-elephant.icon: https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEje4_PBv5ZTOy8CPjTf243_992XCtsC3ZG3yMe8lwkfRfSB-UjbPctl5N-b2BRDiAL8XQBKbz864d2KrQx13bHApg57FDzqkWBBxlnxb_G4yqp6Pe9Yjo9zdKHdAWLWm7IQRc7b-2e8zFo7XB8_dNyuB1kY6mfB042N7TuZWpICoyxIgwReeVwVvF07yds/s1000/akasa3.jpg
krypinet_h0me0ps.physical.compute.standalone.banging-blueberry.style.fill: lightblue
krypinet_h0me0ps.physical.compute.standalone.banging-blueberry.icon: https://www.sensoreq.com/43-large_default/coolipi-4b-chladic-modr.jpg

# cloud compute
internet.hetzner.compute.vm.clp-monitor11.icon: https://upload.wikimedia.org/wikipedia/commons/0/0c/Logo_Hetzner.svg
internet.hostkey.compute.vm.clp-worker11.icon: https://cdn.hostadvice.com/2016/04/hostkey_logo-162x49.png.webp

# network
krypinet_h0me0ps.physical.network.unifi.uswy.icon: https://cf-images.dustin.eu/cdn-cgi/image/format=auto,quality=75,width=828,,fit=contain/image/d200001002250315/ubiquiti-unifi-switch-lite-8-poe.jpg
krypinet_h0me0ps.physical.network.unifi.uswy.style.fill: lightgreen
krypinet_h0me0ps.physical.network.unifi.uswy.icon: https://cf-images.dustin.eu/cdn-cgi/image/format=auto,quality=75,width=828,,fit=contain/image/d200001002250315/ubiquiti-unifi-switch-lite-8-poe.jpg
krypinet_h0me0ps.physical.network.unifi.flexy.style.fill: lightgreen
krypinet_h0me0ps.physical.network.unifi.flexy.icon: https://cf-images.dustin.eu/cdn-cgi/image/format=auto,quality=75,width=828,,fit=contain/image/d200001004238544/ubiquiti-unifi-usw-flex-mini.jpg
krypinet_h0me0ps.physical.network.unifi.proey.style.fill: lightgreen
krypinet_h0me0ps.physical.network.unifi.proey.icon: https://cf-images.dustin.eu/cdn-cgi/image/format=auto,quality=75,width=828,,fit=contain/image/d200001003258012/ubiquiti-unifi-6-lite-accesspunkt.jpg
krypinet_h0me0ps.physical.network.unifi.litey.style.fill: lightgreen
krypinet_h0me0ps.physical.network.unifi.litey.icon: https://cf-images.dustin.eu/cdn-cgi/image/format=auto,quality=75,width=828,,fit=contain/image/d200001003258012/ubiquiti-unifi-6-lite-accesspunkt.jpg

# storage
krypinet_h0me0ps.physical.storage.nas.nasty-nightfish.icon: https://kksb-cases.com/cdn/shop/products/DSC01941_800x448.jpg?v=1664280934
krypinet_h0me0ps.physical.storage.nas.nasty-nightfish.style.fill: lightblue

# cloud storage
internet.microsoft.storage.onedrive.icon: https://upload.wikimedia.org/wikipedia/commons/3/3c/Microsoft_Office_OneDrive_%282019%E2%80%93present%29.svg
internet.backblaze.storage.b2.icon: https://cdn2.iconfinder.com/data/icons/flurry-icons-for-deviants/256/backblaze_256x256x32.png
internet.storadera.storage.s3.icon: https://simplebackups.com/static/05adbaa8bee63b529a8001684b4421d7/2e34e/storadera-ico.webp
internet.hetzner.storage.storagebox.icon: https://upload.wikimedia.org/wikipedia/commons/0/0c/Logo_Hetzner.svg
internet.putio.storage.blob.icon: https://searchvectorlogo.com/wp-content/uploads/2020/10/put-io-logo-vector.png

# vm's
krypinet_h0me0ps.virtual.servers.icon: https://avatars.githubusercontent.com/u/73596424?s=200&v=4

# containers
krypinet_h0me0ps.virtual.services.icon: https://cdn.worldvectorlogo.com/logos/docker.svg

# # virtual networks
virtualnetwork.tailscale.icon: https://tailscale.gallerycdn.vsassets.io/extensions/tailscale/vscode-tailscale/1.0.0/1698786256133/Microsoft.VisualStudio.Services.Icons.Default
virtualnetwork.tailscale.style.fill: grey
tailscale-acls.style.fill: grey
virtualnetwork.cloudflare.icon: https://cdn.iconscout.com/icon/premium/png-512-thumb/cloudflare-2752221-2285038.png?f=webp&w=256
virtualnetwork.cloudflare.style.fill: orange
cloudflare-access.style.fill: orange

# # connections

isp <-> firewall <-> vlans: {style.animated: true}

krypinet_h0me0ps.physical.compute.hypervisors -> vlans: vlan2,vlan4 {
  style: {
    stroke: blue
    opacity: 1
    stroke-width: 8
    stroke-dash: 5
  }
}
krypinet_h0me0ps.physical.storage <-> vlans: vlan3 {
  style: {
    stroke: blue
    opacity: 1
    stroke-width: 8
    stroke-dash: 5
  }
}

krypinet_h0me0ps.physical.compute.standalone <-> vlans: vlan45 {
  style: {
    stroke: blue
    opacity: 1
    stroke-width: 8
    stroke-dash: 5
  }
}
krypinet_h0me0ps.virtual.servers <-> vlans: vlan42,vlan66,vlan99,vlan100 {
  style: {
    stroke: blue
    opacity: 1
    stroke-width: 8
    stroke-dash: 5
  }
}
krypinet_h0me0ps.virtual.services <-> vlans: vlan43,vlan66,vlan99 {
  style: {
    stroke: blue
    opacity: 1
    stroke-width: 8
    stroke-dash: 5
  }
}

krypinet_h0me0ps.virtual.servers <-> tailscale-acls: servers<->ts {
  style: {
    stroke: black
    opacity: 1
    stroke-width: 8
  }
}
krypinet_h0me0ps.physical.compute <-> tailscale-acls: compute<->ts {
  style: {
    stroke: black
    opacity: 1
    stroke-width: 8
  }
}
krypinet_h0me0ps.physical.storage <-> tailscale-acls: compute<->ts {
  style: {
    stroke: black
    opacity: 1
    stroke-width: 8
  }
}

internet.hostkey.compute <-> tailscale-acls: compute<->ts {
  style: {
    stroke: black
    opacity: 1
    stroke-width: 8
  }
}
internet.hetzner.compute <-> tailscale-acls: compute<->ts {
  style: {
    stroke: black
    opacity: 1
    stroke-width: 8
  }
}
tailscale-acls -> virtualnetwork.tailscale: {
  style: {
    stroke: black
    opacity: 1
    stroke-width: 8
  }
}

krypinet_h0me0ps.virtual.servers <-> cloudflare-access: servers<->cf {
  style: {
    stroke: orange
    opacity: 1
    stroke-width: 8
    animated: true
  }
}
krypinet_h0me0ps.virtual.services <-> cloudflare-access: services<->cf {
  style: {
    stroke: orange
    opacity: 1
    stroke-width: 8
    animated: true
  }
}
cloudflare-access -> virtualnetwork.cloudflare -> isp: {
  style: {
    stroke: orange
    opacity: 1
    stroke-width: 8
    animated: true
  }
}

h0me.devices.trusted <-> vlans: vlan11 {
  style: {
    stroke: green
    opacity: 1
    stroke-width: 8
    stroke-dash: 5
  }
}
h0me.devices.guests <-> vlans: vlan12 {
  style: {
    stroke: yellow
    opacity: 1
    stroke-width: 8
    stroke-dash: 5
  }
}
h0me.devices.iot <-> vlans: vlan13 {
  style: {
    stroke: red
    opacity: 1
    stroke-width: 8
    stroke-dash: 5
  }
}

# # internet
isp.wan1clean.shape: cloud
isp.wan1clean.style.fill: lightgreen
isp.wan2dirty.shape: cloud
isp.wan2dirty.style.fill: pink

# objects
firewall.style.fill: lightgrey
firewall.icon: https://raw.githubusercontent.com/loganmarchione/homelab-svg-assets/6c3d6c8b4742ded0d0643aef2c6f7008fdbeb5a7/assets/opnsense.svg
# firewall.near: bottom-center
vlans.switches-n-aps.style.fill: lightgrey
vlans.switches-n-aps.icon: https://raw.githubusercontent.com/loganmarchione/homelab-svg-assets/6c3d6c8b4742ded0d0643aef2c6f7008fdbeb5a7/assets/ubiquiti.svg
vlans: 11,12,13,42,43,45,66,99,100
internet.near: bottom-center
# vlans.style.fill: lightgreen
# switches-n-aps: bottom-right
# internet.shape: cloud
# internet.near: bottom-center
h0me.devices.trusted.style.fill: green
h0me.devices.guests.style.fill: yellow
h0me.devices.iot.style.fill: red
h0me.near: center-left

services.cloudflare11.icon: https://cdn.worldvectorlogo.com/logos/docker.svg
services.cloudflare21.icon: https://cdn.worldvectorlogo.com/logos/docker.svg
services.cloudflare31.icon: https://cdn.worldvectorlogo.com/logos/docker.svg
services.cloudflare31231.icon: https://cdn.worldvectorlogo.com/logos/docker.svg
services.cloudflare31431.icon: https://cdn.worldvectorlogo.com/logos/docker.svg
services.cloudflare31231.icon: https://cdn.worldvectorlogo.com/logos/docker.svg
services.cloudflare3123121.icon: https://cdn.worldvectorlogo.com/logos/docker.svg
services.cloudflare34541.icon: https://cdn.worldvectorlogo.com/logos/docker.svg
services.cloudflare3156767.icon: https://cdn.worldvectorlogo.com/logos/docker.svg
services.near: top-center

field.uptimekuma: {
  link: https://uptimekuma-public.krypi.net/)
}
field.near: top-left
field.style.3d: true
field.style.fill: lightgrey

field.text: |md
  # just a little,
  # sumthin, sumthin of 
  # what i can do!
|
field.colors.text: |md
  <span style="color:blue">BLUE - trust, lab </span>

  <span style="color:yellow">YELLOW - untrust, guest </span>

  <span style="color:red">RED - untrust, iot </span>

  <span style="color:black">BLACK - tailscale </span>

  <span style="color:orange">ORANGE - cf-tunnel </span>
|

field.vlans.text: |md
  - vlan2 trusthypervisors
  - vlan3 truststorage
  - vlan4 trustdocker
  - vlan11 trusthome
  - vlan12 untrustguest
  - vlan13 untrustiot
  - vlan42 trustservers
  - vlan43 trustservices
  - vlan45 trustscanner
  - vlan66 untrustvoid
  - vlan99 untrustingress
  - vlan100 untrustlab
|