vars: {
  d2-config: {
    layout-engine: elk
  }
}

all of the goodies!

title: krypi.net home0ps {
  near: top-center

  shape: text

  style: {
    font-size: 29

    bold: true

    underline: true
  }
}

direction: down

classes: {
  *: {
    label: ""

    shape: circle

    style: {
      border-radius: 10
    }
  }

  vm: {
    style: {
      stroke-dash: 10
    }
  }

  container: {
    style: {
      stroke-dash: 10
    }
  }
}

internet: {
  shape: cloud

  label: "ISP"
}

internet.style: {
  opacity: 1

  fill: pink

  stroke: black
}

edge.modem: {
  explanation: |md



    ## 2x660/60 Mbps

  |
}

edge.modem.style: {
  opacity: 1

  fill: pink

  3d: true

  stroke: black
}

edge.modem: {
  icon: https://www.svgrepo.com/show/294974/router-modem.svg
}

network.vlans.home: {
  explanation: |md



    - SSID: **La La LAN**



  |
}

network.vlans.guest: {
  explanation: |md



    - SSID: **LANdalorian**



  |
}

network.vlans.iot: {
  explanation: |md



    - SSID: **LANibal Lecter**



  |
}

network.vlans.media: {
  explanation: |md



    - SSID: **CandyLAN**



  |
}

network.vlans.hypervisors: {
  icon: https://www.svgrepo.com/show/485146/server-like.svg
}

network.vlans.hypervisors: {
  explanation: |md
    **sexy**

    **edgy**
  |
}

network.vlans.storage: {
  icon: https://www.svgrepo.com/show/29750/server.svg
}

network.vlans.storage: {
  explanation: |md



    **nasty**



  |
}

network.vlans.docker: {
  icon: https://raw.githubusercontent.com/loganmarchione/homelab-svg-assets/refs/heads/main/assets/xcpng.svg
}

network.vlans.docker: {
  explanation: |md

    **plenty**

    krh-dld-docker11 
      


  |
}

network.vlans.mgmt: {
  explanation: |md

    krl-alp-xos-mgmt11


  |
}

network.vlans.servers: {
  explanation: |md



    - 



  |
}

network.vlans.services: {
  explanation: |md



    dockge

    uptimekuma

    healthchecks

    cloudflare

    gatus

    rclone

    filebrowser

  |
}

network.vlans.security: {
  explanation: |md



    krl-alp-sophosxg-fw11

    krl-abp-opnsense-fw21



  |
}

network.vlans.logging: {
  explanation: |md



    krl-clp-oo-logs11



  |
}

edge.modem: {
  explanation: |md



    ## 2x660/60 Mbps

  |
}

network.unifi: {
  icon: https://raw.githubusercontent.com/loganmarchione/homelab-svg-assets/refs/heads/main/assets/ubiquiti.svg
}

network.unifi.router.ultry.style: {
  opacity: 1

  fill: pink

  3d: true

  stroke: black
}

network.unifi.router.ultry: {
  icon: https://www.svgrepo.com/show/294977/router-modem.svg
}

network.unifi.switch.edgy: {
  icon: https://www.svgrepo.com/show/278243/router.svg
}

network.unifi.switch.edgy.style: {
  opacity: 1

  fill: pink

  3d: true

  stroke: black
}

network.unifi.switch.uxy: {
  icon: https://www.svgrepo.com/show/278243/router.svg
}

network.unifi.switch.uxy.style: {
  opacity: 1

  fill: pink

  3d: true

  stroke: black
}

network.unifi.switch.flexy: {
  icon: https://www.svgrepo.com/show/278243/router.svg
}

network.unifi.switch.flexy.style: {
  opacity: 1

  fill: pink

  3d: true

  stroke: black
}

network.unifi.wifi.proey: {
  icon: https://www.svgrepo.com/show/191821/wifi-router.svg
}

network.unifi.wifi.proey.style: {
  opacity: 1

  fill: pink

  3d: true

  stroke: black
}

network.unifi.wifi.litey: {
  icon: https://www.svgrepo.com/show/191821/wifi-router.svg
}

network.unifi.wifi.litey.style: {
  opacity: 1

  fill: lightgreen

  3d: true

  stroke: black
}

internet <-> edge.modem: {style.animated: true}

edge.modem <-> network.unifi.router.ultry: {style.animated: true}

edge.modem <-> network.unifi.router.ultry: {style.animated: true}

network.unifi <-> network.vlans
network.unifi <-> network.vlans

# network.unifi.router.ultry <-> network.unifi.switch.edgy: {style.animated: true}

# network.unifi.switch.edgy <-> network.unifi.switch.uxy: {style.animated: true}

# network.unifi.switch.edgy <-> network.unifi.switch.flexy: {style.animated: true}

# network.unifi.switch.edgy <-> network.unifi.wifi.proey: {style.animated: true}

# network.unifi.wifi.proey <-> network.unifi.wifi.litey: {style.animated: true}

# network.unifi.wifi -> network.wifi.vlans: "vlans 11,12,13,44 - untrusted - mixed auth" {

# style.animated: false

# }

# network.unifi.switch.uxy -> compute.lab.sexy

server: {
  icon: https://www.svgrepo.com/show/485146/server-like.svg
}

server2: {
  icon: https://www.svgrepo.com/show/513345/server.svg
}

firewall: {
  icon: https://www.svgrepo.com/show/246824/firewall.svg
}

wifi: {
  icon: https://www.svgrepo.com/show/191821/wifi-router.svg
}

switch: {
  icon: https://www.svgrepo.com/show/278243/router.svg
}

nas: {
  icon: https://www.svgrepo.com/show/29750/server.svg
}
