services:
  healthchecks:
    image: healthchecks/healthchecks:latest
    container_name: healthchecks
    environment:
      - ALLOWED_HOSTS=cloudflare.domain.com,vanity-subdomain.domain.com
      - DB=sqlite
      - DB_NAME=/tmp/hc.sqlite
      - SITE_ROOT=https://cloudflare.domain.com
      - DEBUG=False
      - SECRET_KEY=xxxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx
      - ADMINS=email-address
      - DEFAULT_FROM_EMAIL=email-address
      - EMAIL_HOST=email-relay.domain.com
      - EMAIL_HOST_USER=apikey
      - EMAIL_HOST_PASSWORD=the_api_key
      - REGISTRATION_OPEN=False
      - PING_EMAIL_DOMAIN=vanity-domain.com
      - PING_ENDPOINT=https://vanity-subdomain.domain.com:8000/ping/
      - SMTPD_PORT=25
      - SITE_NAME=site_name_and_app_name
      - DISCORD_CLIENT_ID=discord_app_oauth_id
      - DISCORD_CLIENT_SECRET=discord_app_oauth_secret
    ports:
      - 8000:8000
      - 25:25
    volumes:
      - healthchecks-data:/data
    restart: unless-stopped
volumes:
  healthchecks-data: null
version: "3.8"
networks: {}
