services:
  shields:
    restart: always
    ports:
      - 8091:8080
    environment:
      - PORT=8080
    container_name: sh-shields-0101
    image: shieldsio/shields:server-2024-03-01
networks: {}
