services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v2
    container_name: sh-pocketid-0101
    restart: "no"
    entrypoint: ["/bin/sh", "-c", "sleep 999999"]   # ✅ override Pocket ID startup
    environment:
      - ENCRYPTION_KEY
    ports:
      - 1411:1411
    volumes:
      - "./data:/app/data"
