services:
  homey-shs:
    image: ghcr.io/athombv/homey-shs:latest
    container_name: sh-homey-shs-0101
    restart: unless-stopped
    #network_mode: ipvlan
    privileged: true
    volumes:
      - /mnt/data/docker/homey-shs:/homey/user
    network_mode: host
      networks:
        ipv-vlan13-iot:
          ipv4_address: 192.168.13.32

  networks:
    ipv-vlan13-iot: 
      driver: ipvlan
      ipam:
        config:
          - subnet: 192.168.13.0/24 # The full available range
            gateway: 192.168.13.1  # The gateway IP for this subnet

