services:
  homey-shs:
    image: ghcr.io/athombv/homey-shs:latest
    container_name: sh-homey-shs-0101
    restart: unless-stopped
    privileged: true
    volumes:
      - /mnt/data/docker/homey-shs:/homey/user
    networks:
      ipvlan-vlan13-iot: 
        ipv4_address: 192.168.13.30
    environment:
      HOMEY_LOCAL_ADDRESS: 192.168.13.32

networks:
  ipvlan-vlan13-iot:
    driver: ipvlan
    driver_opts:
      parent: enp5s0.13
    ipam:
       config:
        - subnet: 192.168.13.0/24
          gateway: 192.168.13.1
