services:
  homey-shs:
    image: ghcr.io/athombv/homey-shs:latest
    container_name: sh-homey-shs-0101
    restart: unless-stopped
    privileged: true
    volumes:
      - /mnt/data/docker/homey-shs:/homey/user
    networks:
      ipv-vlan13-iot: 
        ipv4_address: 192.168.13.2
    environment:
      HOMEY_LOCAL_ADDRESS: 192.168.13.2

networks:
  ipv-vlan13-iot: 
    driver: ipvlan
    ipam:
      config:
        - subnet: 192.168.13.2/27
          gateway: 172.16.23.1
