version: "3"
services:
  vikunja:
    image: vikunja/vikunja
    container_name: vikunja11
    environment:
      VIKUNJA_SERVICE_PUBLICURL: #placeholder -  the actual public url, regardless of proxy....
      VIKUNJA_SERVICE_ENABLEREGISTRATION: 0
      VIKUNJA_DATABASE_HOST: db
      VIKUNJA_DATABASE_PASSWORD: #placeholder
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_DATABASE_USER: vikunja
      VIKUNJA_DATABASE_DATABASE: vikunja
      VIKUNJA_SERVICE_JWTSECRET: placeholder
      VIKUNJA_LOG_LEVEL: DEBUG
    ports:
      - 3456:3456
    volumes:
      - ./files:/app/vikunja/files
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks: {}
  db:
    image: mariadb:10
    container_name: mariadb11
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: #placeholder
      MYSQL_USER: vikunja
      MYSQL_PASSWORD: #placeholder
      MYSQL_DATABASE: vikunja
    volumes:
      - ./db:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - mysqladmin ping -h localhost -u $$MYSQL_USER
          --password=$$MYSQL_PASSWORD
      interval: 2s
      start_period: 30s
    networks: {}
