version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage11
    restart: always
    #environment:
    #PUID: 1000 -- optional, your user id
    #PGID: 1000 -- optional, your group id
    #    docker-socket-proxy:
    #     host: 127.0.0.1
    #    port: 2375
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks: {}
