services:
  archiveTeamWarrior:
    image: atdr.meo.ws/archiveteam/warrior-dockerfile
    container_name: archivewarrior
    hostname: archivewarrior
    ports:
      - 8001:8001
    restart: always
    environment:
      - HTTP_PASSWORD=placeholder ## login pw
      - HTTP_USERNAME=kaplaceholder ## login username
      - SELECTED_PROJECT=urlteam2
      - CONCURRENT_ITEMS=4
      - DOWNLOADER=placeholder ##high score name
networks: {}
version: "3.8"