services:
  archiveTeamWarrior11:
    image: atdr.meo.ws/archiveteam/warrior-dockerfile
    container_name: archivewarrior11
    hostname: archivewarrior11
    expose:
      - 8001
    restart: always
    environment:
      - HTTP_PASSWORD=${{ secrets.ARCHIVETEAMWARRIOR_HTTP_PASSWORD }}
      - HTTP_USERNAME=${{ secrets.ARCHIVETEAMWARRIOR_HTTP_USERNAME }}
      - SELECTED_PROJECT=pastebin
      - CONCURRENT_ITEMS=2
      - DOWNLOADER=morna
    networks:
      - cloudflare
  archiveTeamWarrior12:
    image: atdr.meo.ws/archiveteam/warrior-dockerfile
    container_name: archivewarrior12
    hostname: archivewarrior12
    expose:
      - 8002
    restart: always
    environment:
      - HTTP_PASSWORD=${{ secrets.ARCHIVETEAMWARRIOR_HTTP_PASSWORD }}
      - HTTP_USERNAME=${{ secrets.ARCHIVETEAMWARRIOR_HTTP_USERNAME }}
      - SELECTED_PROJECT=imgur
      - CONCURRENT_ITEMS=2
      - DOWNLOADER=morna
    networks:
      - cloudflare
  archiveTeamWarrior13:
    image: atdr.meo.ws/archiveteam/warrior-dockerfile
    container_name: archivewarrior13
    hostname: archivewarrior13
    expose:
      - 8003
    restart: always
    environment:
      - HTTP_PASSWORD=${{ secrets.ARCHIVETEAMWARRIOR_HTTP_PASSWORD }}
      - HTTP_USERNAME=${{ secrets.ARCHIVETEAMWARRIOR_HTTP_USERNAME }}
      - SELECTED_PROJECT=auto
      - CONCURRENT_ITEMS=2
      - DOWNLOADER=morna
    networks:
      - archiveteamwarrior-cloudflare
networks:
  archiveteamwarrior-cloudflare:
    external: true
