services:
  whoami:
    image: denga/whoami:latest
    container_name: sh-whoami-0101
    ports:
      - "8085:80"
    environment:
      - WHOAMI_NAME=${WHOAMI_WHOAMI_NAME}
     # - env_file: .env
    restart: unless-stopped
    networks:
      - whoami
    healthcheck:
      test: [ "CMD", "/app/pocket-id", "healthcheck" ]
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s      
  networks:
    whoami:
      driver: bridge
