
services:
  whoami:
    image: denga/whoami:latest
    container_name: sh-whoami-0101
    ports:
      - "8085:80"
    #environment:
     # - WHOAMI_NAME=${WHOAMI_WHOAMI_NAME}
    restart: unless-stopped
    #network_mode: ipvlan
    networks:
      ipvlan-vlan13-iot: 
        ipv4_address: 192.168.13.30
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost"]
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s

#networks:
 # ipv-vlan13-iot: 
  #  driver: ipvlan
   # ipam:
    #  config:
     #   - subnet: 192.168.13.0/24
      #    gateway: 192.168.13.1

networks:
  ipvlan-vlan13-iot:
    driver: ipvlan
    driver_opts:
      parent: enp5s0.13
    ipam:
       config:
        - subnet: 192.168.13.0/24
          gateway: 192.168.13.1
