version: "3.9"
services:
  gatus:
    restart: always
    image: twinproduction/gatus:latest
    container_name: sh-gatus-0101
    ports:
      - 8080:8080
    volumes:
      - "/opt/docker/projects/gatus/config:/config"
      - "/opt/docker/projects/gatus/data:/data"
    networks:
      - gatus

networks:
  gatus:
    driver: bridge
