version: "3"
services:
  xen-orchestra:
    restart: unless-stopped
    image: ronivay/xen-orchestra:latest
    container_name: xos11
    stop_grace_period: 1m
    ports:
      - 89:80
    environment:
      - HTTP_PORT=80
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./xo-data:/var/lib/xo-server
      - ./redis-data:/var/lib/redis
    logging:
      driver: json-file
      options:
        max-size: 1M
        max-file: "2"
    networks: {}
