
services:
   uptime-kuma:
     container_name: kuma
     image: louislam/uptime-kuma
     volumes:
       - uptime-kuma:/app/data
     ports:
       - "3001:3001"  # <Host Port>:<Container Port>
     restart: always

volumes:
  uptime-kuma: