#!/bin/sh
#cockpit install with storage and networking
. /etc/os-release
echo "deb http://deb.debian.org/debian ${VERSION_CODENAME}-backports main" > /etc/apt/sources.list.d/backports.list
apt update
apt install -t ${VERSION_CODENAME}-backports cockpit -y
apt install -t ${VERSION_CODENAME}-backports cockpit -y
apt install cockpit-storaged -y
apt install cockpit-networkmanager -y

# install docker and add current user to docker group
curl -fsSL get.docker.com | bash
sudo usermod -a -G docker $USER

#other packages
apt install btop ncdu git tldr cloud-utils nfs-kernel-server gpustat sshfs -y

#fixup
mkdir -p ~/.local/share # because sometimes it's broken apparently

#done?
echo -e "\e[32mdone\e[0m"
